### ISSUE TITLE
Error issue

### ISSUE THREAD

**Issue by eddydev03** [mathigatti/img2txt#2]
Dear Mathigatti,

I feel your idea cool. I try to make it work since 2 days but I donnot succeed yet.

Here the error message on the command prompt on Win 10:
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\img2txt-master\src\table_example.py", line 2, in <module>
    from ocr import Ocr
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\img2txt-master\src\ocr.py", line 1, in <module>
    from googleVisionApi import GoogleVisionApi
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\img2txt-master\src\googleVisionApi.py", line 5, in <module>
    from google.cloud.vision import types
ImportError: cannot import name 'types' from 'google.cloud.vision' (C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\google\cloud\vision\__init__.py)

I have followed the steps for google credentials. I have the credential.json. I even tried by setting manally the env variable but the same error appears. Any thought?

Thank you,

Eddy

**Comment by mathigatti** [comment]
Seems like it doesn't work for the latest vision api version, you should install google-cloud-vision==1.0.0

Try something like: `pip install -U google-cloud-vision==1.0.0`

**Comment by eddydev03** [comment]
Top! I see. Now I am dealing with Google Auth. 

RUNNING ON sample/input/sample.png
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\img2txt-master\src\table_example.py", line 46, in <module>
    main(imagePath)
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\img2txt-master\src\table_example.py", line 13, in main
    ocr = Ocr()
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\img2txt-master\src\ocr.py", line 16, in __init__
    self.googleApi = GoogleVisionApi()
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\img2txt-master\src\googleVisionApi.py", line 11, in __init__
    self.client = vision.ImageAnnotatorClient()
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\site-packages\google\cloud\vision_v1\gapic\image_annotator_client.py", line 164, in __init__
    self.transport = image_annotator_grpc_transport.ImageAnnotatorGrpcTransport(
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\site-packages\google\cloud\vision_v1\gapic\transports\image_annotator_grpc_transport.py", line 65, in __init__
    channel = self.create_channel(
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\site-packages\google\cloud\vision_v1\gapic\transports\image_annotator_grpc_transport.py", line 108, in create_channel
    return google.api_core.grpc_helpers.create_channel(
  File "C:\Users\Magicbook\AppData\Local\Programs\Python\Python39\lib\site-packages\google\api_core\grpc_helpers.py", line 275, in create_channel
    composite_credentials = _create_composite_credentials(
  File "C:\Users\Magicbook\AppData\Local\Programs\Python\Python39\lib\site-packages\google\api_core\grpc_helpers.py", line 217, in _create_composite_credentials
    credentials, _ = google.auth.default(scopes=scopes)
  File "C:\Users\Magicbook\AppData\Local\Programs\Python\Python39\lib\site-packages\google\auth\_default.py", line 340, in default
    credentials, project_id = checker()
  File "C:\Users\Magicbook\AppData\Local\Programs\Python\Python39\lib\site-packages\google\auth\_default.py", line 185, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "C:\Users\Magicbook\AppData\Local\Programs\Python\Python39\lib\site-packages\google\auth\_default.py", line 96, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File credential.json was not found.

I followed all the steps of Installing the client library and Setting up authentication mentioned by cloud google.com.
I created the Json and dowloaded it. I put it in the /src folder and renamed it to credential.json. Checked it, everything is inside the file. Might be the set up auth but I can't find what. I have seen that people do set the auth path on the code but I think it can be done without a hard put in code.

I appriciate your help. Thank you mathigatti

**Comment by mathigatti** [comment]
Try moving the credential.json file to the root folder of the repository

**Comment by eddydev03** [comment]
Yes, I have seen that you changed paths aswell. No error displayed, only a permission denied, I am redirected to enable billing on project to run through it so I guess that it works! Thank you. I have a question then. Is the running of your program in the free Tier of Google Cloud or will I be charged according to my use? 

Sincerely,

**Comment by mathigatti** [comment]
Awesome! I think If you run it for 1000 images or less then it's free, you can check the API vision pricing details.

**Comment by eddydev03** [comment]
Cool, that's great. Thank you for your help. Have a beautiful day.
